'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {createBrowserSupabase} from '@/lib/supabase/browser';
const db=createBrowserSupabase();
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export default function Onboarding(){
 const [userId,setUserId]=useState<string|null>(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [businesses,setBusinesses]=useState<any[]>([]);
 useEffect(()=>{db.auth.getUser().then(({data})=>{setUserId(data.user?.id||null);if(data.user)loadBusinesses()})},[]);
 async function loadBusinesses(){const {data}=await db.from('business_users').select('business_id,role,businesses(id,name,slug)').order('role');setBusinesses(data||[])}
 async function signIn(e:FormEvent){e.preventDefault();setMsg('Signing in...');const {data,error}=await db.auth.signInWithPassword({email:email.trim(),password});if(error){setMsg('Unable to sign in. Check your email and password, confirm your email if required, then try again.');return}setUserId(data.user.id);setMsg('Signed in.');await loadBusinesses()}
 async function signUp(){const cleanEmail=email.trim();if(!cleanEmail||password.length<8){setMsg('Enter a valid email and a password of at least 8 characters.');return}setMsg('Creating account...');const configuredOrigin=(process.env.NEXT_PUBLIC_APP_URL||'').replace(/\/$/,'');const emailRedirectTo=(configuredOrigin||window.location.origin)+'/onboarding';const {data,error}=await db.auth.signUp({email:cleanEmail,password,options:{emailRedirectTo}});if(error){setMsg('Unable to create the account. Check the information and try again.');return}if(data.session){setUserId(data.user?.id||null);setMsg('Account created.')}else setMsg('If the address can be registered, check your email for a confirmation link, then sign in.')}
 async function createBusiness(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!userId)return;const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim(),category=String(f.get('category')||'').trim();if(!name||!category){setMsg('Business name and primary service are required.');return}const {error}=await db.rpc('create_business_with_owner_and_service',{p_name:name,p_slug:slugify(name)+'-'+crypto.randomUUID().slice(0,6),p_category:category,p_phone:String(f.get('phone')||'').trim(),p_website_url:String(f.get('website')||'').trim()});if(error){setMsg(error.message);return}setMsg('Business and primary service created with owner access.');e.currentTarget.reset();await loadBusinesses()}
 async function createHive(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!userId)return;const f=new FormData(e.currentTarget);const name=String(f.get('hiveName')||'').trim();const businessId=String(f.get('businessId')||'');if(!name||!businessId){setMsg('Hive name and founding business are required.');return}const {error}=await db.rpc('create_hive_with_founder',{p_name:name,p_slug:slugify(name)+'-'+crypto.randomUUID().slice(0,6),p_market_name:String(f.get('market')||'').trim(),p_business_id:businessId});if(error){setMsg(error.message);return}setMsg('Hive created atomically with its founding member. It is ready for services and offers.');e.currentTarget.reset()}
 if(!userId)return <main style={{maxWidth:520,margin:'70px auto',padding:22}}><div className="eyebrow">HOME HIVE 360</div><h1 className="title">Founder / Member Access</h1><p className="sub">Sign in to build businesses and Hives.</p><form className="card" onSubmit={signIn}><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></div><br/><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete="current-password"/></div><br/><div style={{display:'flex',gap:8}}><button className="btn" type="submit">Sign In</button><button className="btn secondary" type="button" onClick={signUp}>Create Account</button></div>{msg&&<p className="sub" style={{marginTop:15}}>{msg}</p>}<p className="label" style={{marginTop:18}}><Link href="/auth/forgot-password">Forgot password?</Link></p></form></main>;
 return <main style={{maxWidth:950,margin:'40px auto',padding:22}}><div className="eyebrow">HH360 BUILDER</div><h1 className="title">Build the network</h1><p className="sub">These forms write directly to the secured Home Hive 360 database.</p>{msg&&<div className="card" style={{marginBottom:16}}>{msg}</div>}<div className="two"><form className="card" onSubmit={createBusiness}><h2>1. Create Business</h2><div className="field"><label>Business name</label><input name="name" required/></div><br/><div className="field"><label>Primary service category</label><input name="category" placeholder="HVAC, Plumbing, Roofing..." required/></div><br/><div className="field"><label>Phone</label><input name="phone" autoComplete="tel"/></div><br/><div className="field"><label>Website</label><input name="website" type="url" placeholder="https://"/></div><br/><button className="btn">Create Business</button></form><form className="card" onSubmit={createHive}><h2>2. Create Hive</h2><div className="field"><label>Hive name</label><input name="hiveName" required/></div><br/><div className="field"><label>Market</label><input name="market" placeholder="Golden Isles, Georgia" required/></div><br/><div className="field"><label>Founding business</label><select name="businessId" required><option value="">Select business</option>{businesses.map((x:any)=><option key={x.business_id} value={x.business_id}>{x.businesses?.name}</option>)}</select></div><br/><button className="btn">Create Hive</button></form></div><section className="section card"><div className="sectionHead"><b>Your Businesses</b><button className="btn secondary" onClick={async()=>{await db.auth.signOut();setUserId(null);setBusinesses([])}}>Sign Out</button></div>{businesses.length?businesses.map((x:any)=><div key={x.business_id} style={{padding:'10px 0',borderBottom:'1px solid #e4eae4'}}><b>{x.businesses?.name}</b> <span className="badge">{x.role}</span></div>):<p className="sub">Create your first business above.</p>}</section></main>
}
