import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Not configured'},{status:503});
 let body:{hiveSlug?:string;businessSlug?:string;sourceSlug?:string;pid?:string;offerId?:string;eventType?:string};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}
 if(!body.hiveSlug||!body.businessSlug)return NextResponse.json({error:'Missing target'},{status:422});
 const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const rate=await db.rpc('consume_api_rate_limit',{p_bucket_key:'public:click:'+(request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown'),p_window_seconds:60,p_limit:180});if(rate.error)return NextResponse.json({error:'Rate limiter unavailable'},{status:503});if(!rate.data)return NextResponse.json({error:'Rate limit exceeded'},{status:429,headers:{'Retry-After':'60'}});
 const [hiveResult,businessResult]=await Promise.all([db.from('hives').select('id').eq('slug',body.hiveSlug).eq('status','active').maybeSingle(),db.from('businesses').select('id').eq('slug',body.businessSlug).eq('status','active').maybeSingle()]);if(hiveResult.error||businessResult.error)return NextResponse.json({error:'Target lookup failed'},{status:500});const hive=hiveResult.data,business=businessResult.data;if(!hive||!business)return NextResponse.json({error:'Not found'},{status:404});
 const memberResult=await db.from('hive_members').select('business_id').eq('hive_id',hive.id).eq('business_id',business.id).eq('status','active').maybeSingle();if(memberResult.error)return NextResponse.json({error:'Membership lookup failed'},{status:500});const member=memberResult.data;if(!member)return NextResponse.json({error:'Not found'},{status:404});
 if(body.eventType&&body.eventType!=='member.clicked'&&body.eventType!=='offer.clicked')return NextResponse.json({error:'Invalid event type'},{status:422});
 if(body.eventType==='offer.clicked'&&!body.offerId)return NextResponse.json({error:'Offer click requires offerId'},{status:422});
 if(body.eventType==='member.clicked'&&body.offerId)return NextResponse.json({error:'Member click cannot include offerId'},{status:422});
 let delivery:any=null;if(body.pid){const deliveryResult=await db.from('promotion_deliveries').select('id,lead_id,hive_id,source_business_id,customer_id,campaign_id,status').eq('tracking_token',body.pid).maybeSingle();if(deliveryResult.error)return NextResponse.json({error:'Promotion lookup failed'},{status:500});delivery=deliveryResult.data;if(!delivery||delivery.hive_id!==hive.id||!['sent','delivered'].includes(delivery.status))return NextResponse.json({error:'Invalid promotion token'},{status:422});}
 if(body.offerId){const now=new Date().toISOString();let offerQuery=db.from('offers').select('id,status,starts_at,ends_at').eq('id',body.offerId).eq('business_id',business.id).or('hive_id.eq.'+hive.id+',hive_id.is.null');const offerResult=await offerQuery.maybeSingle();if(offerResult.error)return NextResponse.json({error:'Offer lookup failed'},{status:500});const offer=offerResult.data;if(!offer)return NextResponse.json({error:'Invalid offer'},{status:422});if(delivery?.campaign_id){const campaignResult=await db.from('hive_campaigns').select('spotlight_offer_id').eq('id',delivery.campaign_id).maybeSingle();if(campaignResult.error)return NextResponse.json({error:'Campaign lookup failed'},{status:500});const isFrozenSpotlightOffer=campaignResult.data?.spotlight_offer_id===body.offerId;if(!isFrozenSpotlightOffer&&(offer.status!=='active'||(offer.starts_at&&offer.starts_at>now)||(offer.ends_at&&offer.ends_at<now)))return NextResponse.json({error:'Invalid offer'},{status:422});}else if(offer.status!=='active'||(offer.starts_at&&offer.starts_at>now)||(offer.ends_at&&offer.ends_at<now))return NextResponse.json({error:'Invalid offer'},{status:422});}
 let sourceId=delivery?.source_business_id||null;let sourceSlug:string|null=null;if(delivery){const sourceResult=await db.from('businesses').select('slug').eq('id',delivery.source_business_id).maybeSingle();if(sourceResult.error)return NextResponse.json({error:'Promotion source lookup failed'},{status:500});sourceSlug=sourceResult.data?.slug||null;}if(!sourceId&&body.sourceSlug){const sourceBusinessResult=await db.from('businesses').select('id').eq('slug',body.sourceSlug).eq('status','active').maybeSingle();if(sourceBusinessResult.error)return NextResponse.json({error:'Promotion source lookup failed'},{status:500});const sourceBusiness=sourceBusinessResult.data;if(sourceBusiness){const sourceMemberResult=await db.from('hive_members').select('business_id').eq('hive_id',hive.id).eq('business_id',sourceBusiness.id).eq('status','active').maybeSingle();if(sourceMemberResult.error)return NextResponse.json({error:'Promotion source membership lookup failed'},{status:500});if(sourceMemberResult.data){sourceId=sourceBusiness.id;sourceSlug=body.sourceSlug;}}}
 let opportunityId:string|null=null;const isSourceBusiness=Boolean(delivery)&&delivery.source_business_id===business.id;const qualifiesAsOpportunity=Boolean(delivery)&&!isSourceBusiness&&body.eventType==='offer.clicked'&&Boolean(body.offerId);if(qualifiesAsOpportunity){const opportunityResult=await db.rpc('create_promotion_engagement_opportunity',{p_lead_id:delivery.lead_id,p_hive_id:hive.id,p_source_business_id:delivery.source_business_id,p_receiving_business_id:business.id,p_offer_id:body.offerId,p_campaign_id:delivery.campaign_id||null});if(opportunityResult.error)return NextResponse.json({error:'Opportunity creation failed'},{status:500});opportunityId=opportunityResult.data||null;}
 const eventType=body.offerId?'offer.clicked':'member.clicked';
 const eventKey=delivery?'click:'+delivery.id+':'+business.id+':'+(body.offerId||'member')+':'+eventType:'organic:'+hive.id+':'+business.id+':'+(body.offerId||'member')+':'+eventType+':'+new Date().toISOString().slice(0,13);
 const result=await db.rpc('record_public_attribution_event',{p_event_key:eventKey,p_hive_id:hive.id,p_business_id:business.id,p_customer_id:delivery?.customer_id||null,p_lead_id:delivery?.lead_id||null,p_event_type:eventType,p_properties:{delivery_id:delivery?.id||null,source_business_id:sourceId,source_slug:sourceSlug,target_business_id:business.id,opportunity_id:opportunityId,offer_id:body.offerId||null,campaign_id:delivery?.campaign_id||null,channel:'hive_page',is_source_business:isSourceBusiness,attributed:!isSourceBusiness&&Boolean(delivery)}});
 if(result.error)return NextResponse.json({error:'Event not recorded'},{status:500});return NextResponse.json({ok:true,attributed:!isSourceBusiness&&Boolean(delivery),opportunity_created:Boolean(opportunityId),recorded:Boolean(result.data)});
}