import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Not configured'},{status:503});
 let body:{hiveSlug?:string;businessSlug?:string;sourceSlug?:string;pid?:string;offerId?:string;eventType?:string};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}
 if(!body.hiveSlug||!body.businessSlug)return NextResponse.json({error:'Missing target'},{status:422});
 const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const rate=await db.rpc('consume_api_rate_limit',{p_bucket_key:'public:click:'+(request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown'),p_window_seconds:60,p_limit:180});if(rate.error)return NextResponse.json({error:'Rate limiter unavailable'},{status:503});if(!rate.data)return NextResponse.json({error:'Rate limit exceeded'},{status:429,headers:{'Retry-After':'60'}});
 const [hiveResult,businessResult]=await Promise.all([db.from('hives').select('id').eq('slug',body.hiveSlug).eq('status','active').maybeSingle(),db.from('businesses').select('id').eq('slug',body.businessSlug).eq('status','active').maybeSingle()]);if(hiveResult.error||businessResult.error)return NextResponse.json({error:'Target lookup failed'},{status:500});const hive=hiveResult.data,business=businessResult.data;if(!hive||!business)return NextResponse.json({error:'Not found'},{status:404});
 const memberResult=await db.from('hive_members').select('business_id').eq('hive_id',hive.id).eq('business_id',business.id).eq('status','active').maybeSingle();if(memberResult.error)return NextResponse.json({error:'Membership lookup failed'},{status:500});const member=memberResult.data;if(!member)return NextResponse.json({error:'Not found'},{status:404});
 if(body.eventType&&body.eventType!=='member.clicked'&&body.eventType!=='offer.clicked')return NextResponse.json({error:'Invalid event type'},{status:422});
 if(body.eventType==='offer.clicked'&&!body.offerId)return NextResponse.json({error:'Offer click requires offerId'},{status:422});
 if(body.eventType==='member.clicked'&&body.offerId)return NextResponse.json({error:'Member click cannot include offerId'},{status:422});
 if(body.offerId){const now=new Date().toISOString();const offerResult=await db.from('offers').select('id').eq('id',body.offerId).eq('business_id',business.id).eq('status','active').or('hive_id.eq.'+hive.id+',hive_id.is.null').or('starts_at.is.null,starts_at.lte.'+now).or('ends_at.is.null,ends_at.gte.'+now).maybeSingle();if(offerResult.error)return NextResponse.json({error:'Offer lookup failed'},{status:500});const offer=offerResult.data;if(!offer)return NextResponse.json({error:'Invalid offer'},{status:422});}
 let delivery:any=null;if(body.pid){const deliveryResult=await db.from('promotion_deliveries').select('id,lead_id,hive_id,source_business_id,customer_id').eq('tracking_token',body.pid).maybeSingle();if(deliveryResult.error)return NextResponse.json({error:'Promotion lookup failed'},{status:500});delivery=deliveryResult.data;if(!delivery||delivery.hive_id!==hive.id)return NextResponse.json({error:'Invalid promotion token'},{status:422});if(delivery.source_business_id===business.id)return NextResponse.json({error:'Promotion source cannot attribute an opportunity to itself'},{status:422});}
 let sourceId=delivery?.source_business_id||null;let sourceSlug:string|null=null;if(delivery){const sourceResult=await db.from('businesses').select('slug').eq('id',delivery.source_business_id).maybeSingle();if(sourceResult.error)return NextResponse.json({error:'Promotion source lookup failed'},{status:500});sourceSlug=sourceResult.data?.slug||null;}if(!sourceId&&body.sourceSlug){const sourceBusinessResult=await db.from('businesses').select('id').eq('slug',body.sourceSlug).eq('status','active').maybeSingle();if(sourceBusinessResult.error)return NextResponse.json({error:'Promotion source lookup failed'},{status:500});const sourceBusiness=sourceBusinessResult.data;if(sourceBusiness){const sourceMemberResult=await db.from('hive_members').select('business_id').eq('hive_id',hive.id).eq('business_id',sourceBusiness.id).eq('status','active').maybeSingle();if(sourceMemberResult.error)return NextResponse.json({error:'Promotion source membership lookup failed'},{status:500});if(sourceMemberResult.data){sourceId=sourceBusiness.id;sourceSlug=body.sourceSlug;}}}
 let opportunityId:string|null=null;if(delivery){const opportunityResult=await db.from('opportunities').select('id').eq('lead_id',delivery.lead_id).eq('receiving_business_id',business.id).maybeSingle();if(opportunityResult.error)return NextResponse.json({error:'Opportunity lookup failed'},{status:500});opportunityId=opportunityResult.data?.id||null;}
 const eventType=body.offerId?'offer.clicked':'member.clicked';
 const eventKey=delivery?'click:'+delivery.id+':'+business.id+':'+(body.offerId||'member')+':'+eventType:'organic:'+hive.id+':'+business.id+':'+(body.offerId||'member')+':'+eventType+':'+new Date().toISOString().slice(0,13);
 const result=await db.rpc('record_public_attribution_event',{p_event_key:eventKey,p_hive_id:hive.id,p_business_id:business.id,p_customer_id:delivery?.customer_id||null,p_lead_id:delivery?.lead_id||null,p_event_type:eventType,p_properties:{delivery_id:delivery?.id||null,source_business_id:sourceId,source_slug:sourceSlug,target_business_id:business.id,opportunity_id:opportunityId,offer_id:body.offerId||null,channel:'hive_page'}});
 if(result.error)return NextResponse.json({error:'Event not recorded'},{status:500});return NextResponse.json({ok:true,attributed:Boolean(delivery),recorded:Boolean(result.data)});
}