'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Offer={id:string;title:string;status:string;business_id:string;hive_id:string|null;cta_label:string|null};
export default function Marketing(){
 const [offers,setOffers]=useState<Offer[]>([]),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);const q=await db.from('offers').select('id,title,status,business_id,hive_id,cta_label').order('created_at',{ascending:false}).limit(100);setOffers((q.data||[]) as Offer[]);setLoading(false);})();},[]);
 const active=useMemo(()=>offers.filter(o=>o.status==='active').length,[offers]);
 return <Shell><div className="eyebrow">Promotion Engine</div><h1 className="title">Marketing</h1><p className="sub">Turn member-generated demand into controlled, consent-aware exposure for complementary Hive businesses.</p>
 <div className="grid"><div className="card"><span className="label">Visible Offers</span><div className="metric">{loading?'—':offers.length}</div></div><div className="card"><span className="label">Active Offers</span><div className="metric">{loading?'—':active}</div></div><div className="card"><span className="label">Selection</span><div className="metric">Top 3</div><span className="label">Deterministic MVP ranking</span></div><div className="card"><span className="label">Consent Gate</span><div className="metric">ON</div><span className="label">Email or SMS permission required</span></div></div>
 <section className="section card"><div className="sectionHead"><div><b>Promotion Rules</b><div className="label">The MVP prioritizes active offers from complementary Hive members and excludes the originating business.</div></div><span className="badge">RULES ENGINE</span></div><div className="funnel" style={{marginTop:14}}><div className="step"><span className="label">1</span><b>Lead Received</b></div><div className="step"><span className="label">2</span><b>Consent Checked</b></div><div className="step"><span className="label">3</span><b>Members Ranked</b></div><div className="step"><span className="label">4</span><b>Top Offers</b></div><div className="step"><span className="label">5</span><b>Track Response</b></div></div></section>
 <section className="section card"><div className="sectionHead"><div><b>Member Offers</b><div className="label">Offers available to businesses you are authorized to access.</div></div><span className="badge">PRIVATE</span></div>{!signedIn&&!loading?<div style={{padding:'30px 0',textAlign:'center'}}><h2>Sign in to manage promotions</h2></div>:null}{signedIn&&!loading&&!offers.length?<div style={{padding:'30px 0',textAlign:'center'}}><h2>No offers yet</h2><p className="sub">Create member offers during the Hive setup workflow.</p></div>:null}{offers.length?<div style={{display:'grid',gap:10,marginTop:18}}>{offers.map(o=><div className="step" key={o.id}><div><b>{o.title}</b><div className="label">{o.cta_label||'Request Service'}</div></div><span className="badge">{o.status.toUpperCase()}</span></div>)}</div>:null}</section></Shell>;
}