'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Opp={id:string;status:string;estimated_value:number|null;closed_value:number|null;created_at:string};
const STAGES=['new','accepted','contacted','qualified','won','lost'];
export default function Opportunities(){
 const [rows,setRows]=useState<Opp[]>([]);const [loading,setLoading]=useState(true);const [signedIn,setSignedIn]=useState(false);const [busy,setBusy]=useState('');
 async function load(){const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);const q=await db.from('opportunities').select('id,status,estimated_value,closed_value,created_at').order('created_at',{ascending:false}).limit(100);setRows((q.data||[]) as Opp[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function update(id:string,patch:Record<string,unknown>){setBusy(id);const db=createBrowserSupabase();const session=await db.auth.getSession();const token=session.data.session?.access_token;if(token){const result=await fetch('/api/v1/opportunities/'+id,{method:'PATCH',headers:{'content-type':'application/json','authorization':'Bearer '+token},body:JSON.stringify(patch)});if(result.ok)await load();}setBusy('');}
 const stats=useMemo(()=>({fresh:rows.filter(o=>o.status==='new').length,progress:rows.filter(o=>['accepted','contacted','qualified'].includes(o.status)).length,pipeline:rows.filter(o=>!['won','lost'].includes(o.status)).reduce((n,o)=>n+Number(o.estimated_value||0),0),revenue:rows.reduce((n,o)=>n+Number(o.closed_value||0),0)}),[rows]);
 const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
 return <Shell><div className="eyebrow">Revenue Attribution</div><h1 className="title">Opportunities</h1><p className="sub">Move Hive referrals through the sales lifecycle and turn network activity into measurable pipeline and revenue.</p><div className="grid"><div className="card"><span className="label">New</span><div className="metric">{loading?'—':stats.fresh}</div></div><div className="card"><span className="label">In Progress</span><div className="metric">{loading?'—':stats.progress}</div></div><div className="card"><span className="label">Pipeline</span><div className="metric">{loading?'—':money(stats.pipeline)}</div></div><div className="card"><span className="label">Attributed Revenue</span><div className="metric">{loading?'—':money(stats.revenue)}</div></div></div><section className="section card"><div className="sectionHead"><div><b>Opportunity Pipeline</b><div className="label">Receiving business owners, admins and managers can update their own opportunities.</div></div><span className="badge">PRIVATE</span></div>{!signedIn&&!loading?<div style={{padding:'34px 0',textAlign:'center'}}><h2>Sign in to view opportunities</h2></div>:null}{signedIn&&!loading&&rows.length===0?<div style={{padding:'34px 0',textAlign:'center'}}><h2>No opportunities yet</h2><p className="sub">Eligible member-generated leads will create attributed opportunities here.</p></div>:null}{rows.length>0?<div style={{display:'grid',gap:10,marginTop:18}}>{rows.map(o=><div className="step" key={o.id}><div><span className="label">{new Date(o.created_at).toLocaleDateString()}</span><b style={{display:'block'}}>Opportunity {o.id.slice(0,8)}</b><span className="label">Estimated {money(Number(o.estimated_value||0))}</span></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><select aria-label="Opportunity status" value={o.status} disabled={busy===o.id} onChange={e=>update(o.id,{status:e.target.value})}>{STAGES.map(stage=><option key={stage} value={stage}>{stage.toUpperCase()}</option>)}</select>{o.status==='won'?<input aria-label="Closed revenue" type="number" min="0" defaultValue={o.closed_value||''} placeholder="Revenue" onBlur={e=>{const amount=Number(e.target.value);if(Number.isFinite(amount)&&amount>=0)update(o.id,{closed_value:amount});}}/>:null}<span className="badge">{o.status.toUpperCase()}</span></div></div>)}</div>:null}</section></Shell>;
}
