import {NextRequest,NextResponse} from 'next/server';
import {authorizeBusinessKey} from '@/lib/api/businessKey';
import {consumeRateLimit} from '@/lib/api/rateLimit';
import {buildPromotionMessage} from '@/lib/promotion/message';
import {sendEmail,sendSms} from '@/lib/promotion/providers';

export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Not configured'},{status:503});
 let body:{delivery_id?:string};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}if(!body.delivery_id)return NextResponse.json({error:'Missing delivery_id'},{status:422});
 const authResult=await authorizeBusinessKey(request,url,secret);if(!authResult.ok)return NextResponse.json({error:authResult.error},{status:authResult.status});const auth=authResult.auth,db=auth.db;const rate=await consumeRateLimit(db,'promotion:send:'+auth.keyId,60,60);if(!rate.ok)return NextResponse.json({error:rate.error||'Rate limit exceeded'},{status:rate.error?503:429,headers:rate.error?undefined:{'Retry-After':'60'}});
 const deliveryResult=await db.from('promotion_deliveries').select('id,status,channel,tracking_token,lead_id,source_business_id,sending_at').eq('id',body.delivery_id).maybeSingle();if(deliveryResult.error)return NextResponse.json({error:'Delivery lookup failed'},{status:500});const delivery=deliveryResult.data;if(!delivery)return NextResponse.json({error:'Delivery not found'},{status:404});if(delivery.source_business_id!==auth.businessId)return NextResponse.json({error:'Forbidden'},{status:403});const recovering=delivery.status==='sending'&&delivery.channel==='email';if(delivery.status!=='queued'&&!recovering)return NextResponse.json({error:'Delivery is not queued',status:delivery.status},{status:409});
 const leadResult=await db.from('leads').select('hive_id,customer_id,marketing_email_allowed,marketing_sms_allowed').eq('id',delivery.lead_id).maybeSingle();if(leadResult.error)return NextResponse.json({error:'Lead lookup failed'},{status:500});const lead=leadResult.data;if(!lead)return NextResponse.json({error:'Lead not found'},{status:404});
 const [customer,source,hive]=await Promise.all([db.from('customers').select('first_name,email,phone,source_business_id').eq('id',lead.customer_id).maybeSingle(),db.from('businesses').select('name,slug,status').eq('id',delivery.source_business_id).maybeSingle(),db.from('hives').select('slug,market_name,status').eq('id',lead.hive_id).maybeSingle()]);if(customer.error||source.error||hive.error)return NextResponse.json({error:'Promotion context lookup failed'},{status:500});if(!customer.data||!source.data||!hive.data)return NextResponse.json({error:'Promotion context incomplete'},{status:409});if(customer.data.source_business_id!==delivery.source_business_id)return NextResponse.json({error:'Promotion customer does not belong to source business'},{status:409});if(source.data.status!=='active'||hive.data.status!=='active')return NextResponse.json({error:'Promotion source or Hive is not active'},{status:409});
 const membershipResult=await db.from('hive_members').select('business_id').eq('hive_id',lead.hive_id).eq('business_id',delivery.source_business_id).eq('status','active').maybeSingle();if(membershipResult.error)return NextResponse.json({error:'Hive membership lookup failed'},{status:500});const membership=membershipResult.data;if(!membership)return NextResponse.json({error:'Promotion source is not an active Hive member'},{status:409});
 let base;try{base=buildPromotionMessage({firstName:customer.data.first_name||'there',sourceBusinessName:source.data.name,hiveSlug:hive.data.slug,sourceBusinessSlug:source.data.slug,marketName:hive.data.market_name,appOrigin:process.env.NEXT_PUBLIC_APP_URL});}catch{return NextResponse.json({error:'Promotion link configuration unavailable'},{status:503});}const hiveUrl=base.hiveUrl+(base.hiveUrl.includes('?')?'&':'?')+'pid='+encodeURIComponent(delivery.tracking_token);
 if(delivery.channel!=='email'&&delivery.channel!=='sms')return NextResponse.json({error:'Unsupported delivery channel'},{status:422});
 if(delivery.channel==='email'&&(!lead.marketing_email_allowed||!customer.data.email))return NextResponse.json({error:'Email consent or destination unavailable'},{status:403});
 if(delivery.channel==='sms'&&(!lead.marketing_sms_allowed||!customer.data.phone))return NextResponse.json({error:'SMS consent or destination unavailable'},{status:403});
 if(recovering){const recovery=await db.rpc('claim_stale_email_delivery_recovery',{p_id:delivery.id,p_stale_seconds:300});if(recovery.error)return NextResponse.json({error:'Email delivery is still processing or cannot be recovered'},{status:409});}else{const claim=await db.rpc('claim_promotion_delivery_for_send',{p_id:delivery.id});if(claim.error)return NextResponse.json({error:'Delivery is already being processed or is no longer queued'},{status:409});}
 let result;if(delivery.channel==='email'){result=await sendEmail({to:customer.data.email,subject:base.emailSubject,text:base.emailText.replace(base.hiveUrl,hiveUrl),idempotencyKey:'promotion/'+delivery.id});}else if(delivery.channel==='sms'){result=await sendSms({to:customer.data.phone,text:base.smsText.replace(base.hiveUrl,hiveUrl)});}else{return NextResponse.json({error:'Unsupported delivery channel'},{status:422});}
 if(!result.ok){if(recovering)return NextResponse.json({error:'Email recovery provider request failed; delivery remains recoverable',detail:result.error},{status:503});const failed=await db.rpc('update_promotion_delivery_atomic',{p_id:delivery.id,p_expected_status:'sending',p_status:'failed',p_provider_message_id:null});if(failed.error)return NextResponse.json({error:'Provider send failed and delivery audit update failed'},{status:500});return NextResponse.json({error:result.error},{status:503});}
 const updated=await db.rpc('update_promotion_delivery_atomic',{p_id:delivery.id,p_expected_status:'sending',p_status:'sent',p_provider_message_id:result.providerMessageId});if(updated.error)return NextResponse.json({error:'Message sent but delivery audit update failed',provider_message_id:result.providerMessageId},{status:500});
 return NextResponse.json({ok:true,delivery:updated.data,provider_message_id:result.providerMessageId});
}
