import {NextRequest,NextResponse} from 'next/server';
import {authorizeBusinessKey} from '@/lib/api/businessKey';
const allowed:Record<string,string[]>={queued:['sent','failed'],sent:['delivered','failed'],delivered:[],failed:[]};
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Not configured'},{status:503});
 let body:{delivery_id?:string;provider_message_id?:string;status?:'sent'|'delivered'|'failed'};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}
 if(!body.delivery_id||!body.status)return NextResponse.json({error:'Missing delivery fields'},{status:422});if(!['sent','delivered','failed'].includes(body.status))return NextResponse.json({error:'Invalid status'},{status:422});
 const auth=await authorizeBusinessKey(request,url,secret);if(!auth)return NextResponse.json({error:'Invalid API key'},{status:401});const db=auth.db;
 const delivery=(await db.from('promotion_deliveries').select('id,status,channel,lead_id,hive_id,source_business_id,customer_id,provider_message_id').eq('id',body.delivery_id).maybeSingle()).data;if(!delivery)return NextResponse.json({error:'Delivery not found'},{status:404});if(delivery.source_business_id!==auth.businessId)return NextResponse.json({error:'Forbidden'},{status:403});
 if(delivery.status===body.status)return NextResponse.json({ok:true,status:delivery.status,duplicate:true});
 if(!(allowed[delivery.status]||[]).includes(body.status))return NextResponse.json({error:'Invalid delivery transition',from:delivery.status,to:body.status},{status:409});
 const now=new Date().toISOString();const patch:Record<string,unknown>={status:body.status};if(body.provider_message_id)patch.provider_message_id=body.provider_message_id;if(body.status==='sent')patch.sent_at=now;if(body.status==='delivered')patch.delivered_at=now;
 const updated=await db.from('promotion_deliveries').update(patch).eq('id',delivery.id).eq('status',delivery.status).select('id,status,channel,provider_message_id,sent_at,delivered_at').maybeSingle();if(updated.error||!updated.data)return NextResponse.json({error:'Delivery changed concurrently; retry with current state'},{status:409});
 const eventType=body.status==='sent'?'promotion.sent':body.status==='delivered'?'promotion.delivered':'promotion.failed';const event=await db.from('events').insert({hive_id:delivery.hive_id,business_id:delivery.source_business_id,customer_id:delivery.customer_id,lead_id:delivery.lead_id,event_type:eventType,actor_type:'system',properties:{delivery_id:delivery.id,channel:delivery.channel,provider_message_id:body.provider_message_id||delivery.provider_message_id||null,from_status:delivery.status,to_status:body.status}});
 if(event.error)return NextResponse.json({error:'Delivery updated but event recording failed',delivery:updated.data},{status:500});return NextResponse.json({ok:true,delivery:updated.data,event_type:eventType});
}