'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Biz={id:string;name:string;slug:string;status:string;website_url:string|null;phone:string|null};
type Service={business_id:string;category:string|null;name:string};
type Membership={business_id:string;hive_id:string;status:string;hives:unknown};
type HiveView={name:string};
const hiveOf=(v:unknown):HiveView|null=>{const x=Array.isArray(v)?v[0]:v;return x&&typeof x==='object'?x as HiveView:null};
const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export default function Businesses(){
 const [biz,setBiz]=useState<Biz[]>([]),[services,setServices]=useState<Service[]>([]),[members,setMembers]=useState<Membership[]>([]),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 async function load(){const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);const [b,s,m]=await Promise.all([db.from('businesses').select('id,name,slug,status,website_url,phone').order('name'),db.from('services').select('business_id,category,name').eq('is_active',true),db.from('hive_members').select('business_id,hive_id,status,hives(name)').eq('status','active')]);setBiz((b.data||[]) as Biz[]);setServices((s.data||[]) as Service[]);setMembers((m.data||[]) as unknown as Membership[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 const rows=useMemo(()=>biz.map(b=>({b,category:services.find(s=>s.business_id===b.id)?.category||services.find(s=>s.business_id===b.id)?.name||'—',hives:members.filter(m=>m.business_id===b.id).map(m=>hiveOf(m.hives)?.name).filter(Boolean).join(', ')||'—'})),[biz,services,members]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage('');const form=new FormData(e.currentTarget),name=String(form.get('name')||'').trim(),category=String(form.get('category')||'').trim(),website=String(form.get('website')||'').trim(),phone=String(form.get('phone')||'').trim();if(!name||!category){setMessage('Business name and service category are required.');setSaving(false);return;}const db=createBrowserSupabase();const auth=await db.auth.getUser();const user=auth.data.user;if(!user){setMessage('Sign in first.');setSaving(false);return;}const slug=slugify(name)+'-'+crypto.randomUUID().slice(0,6);const created=await db.rpc('create_business_with_owner',{p_name:name,p_slug:slug,p_phone:phone||'',p_website_url:website||''});if(created.error||!created.data){setMessage(created.error?.message||'Could not create business.');setSaving(false);return;}const service=await db.from('services').insert({business_id:created.data as string,name:category,category,is_active:true});setMessage(service.error?'Business created; service needs attention.':'Business created successfully.');(e.target as HTMLFormElement).reset();await load();setSaving(false);}
 return <Shell><div className="eyebrow">Member Management</div><div className="sectionHead"><div><h1 className="title">Businesses</h1><p className="sub">Manage the companies and services that power each Hive.</p></div></div>{!signedIn&&!loading?<section className="card"><h2>Sign in to manage businesses</h2></section>:null}<section className="card"><table className="table"><thead><tr><th>Business</th><th>Category</th><th>Hive</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.b.id}><td>{x.b.name}</td><td>{x.category}</td><td>{x.hives}</td><td><span className="badge">{x.b.status}</span></td></tr>)}</tbody></table>{!loading&&rows.length===0?<p className="sub">No businesses yet.</p>:null}</section>{signedIn?<section className="section card"><h2>Add a Business</h2><form className="formGrid" onSubmit={submit}><div className="field"><label>Business name</label><input name="name" required placeholder="Example Home Services"/></div><div className="field"><label>Service category</label><input name="category" required placeholder="HVAC, Plumbing, Roofing..."/></div><div className="field"><label>Website</label><input name="website" placeholder="https://"/></div><div className="field"><label>Phone</label><input name="phone" placeholder="(000) 000-0000"/></div><div><button className="btn" disabled={saving}>{saving?'Saving…':'Save Business'}</button></div>{message?<div className="field full"><span className="label">{message}</span></div>:null}</form></section>:null}</Shell>;
}
