import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({ok:false},{status:503});
 let body:{pid?:string;hiveSlug?:string};try{body=await request.json();}catch{return NextResponse.json({ok:false},{status:400});}if(!body.pid||!body.hiveSlug)return NextResponse.json({ok:false},{status:422});
 const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const rate=await db.rpc('consume_api_rate_limit',{p_bucket_key:'public:visit:'+(request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown'),p_window_seconds:60,p_limit:120});if(rate.error)return NextResponse.json({error:'Rate limiter unavailable'},{status:503});if(!rate.data)return NextResponse.json({error:'Rate limit exceeded'},{status:429,headers:{'Retry-After':'60'}});const deliveryResult=await db.from('promotion_deliveries').select('id,lead_id,hive_id,source_business_id,customer_id').eq('tracking_token',body.pid).maybeSingle();if(deliveryResult.error)return NextResponse.json({ok:false,error:'Attribution lookup failed'},{status:500});const delivery=deliveryResult.data;if(!delivery)return NextResponse.json({ok:false},{status:404});
 const hiveResult=await db.from('hives').select('slug,status').eq('id',delivery.hive_id).maybeSingle();if(hiveResult.error)return NextResponse.json({ok:false,error:'Hive lookup failed'},{status:500});const hive=hiveResult.data;if(!hive||hive.status!=='active'||hive.slug!==body.hiveSlug)return NextResponse.json({ok:false},{status:404});
 const event=await db.rpc('record_public_attribution_event',{p_event_key:'visit:'+delivery.id,p_hive_id:delivery.hive_id,p_business_id:delivery.source_business_id,p_customer_id:delivery.customer_id,p_lead_id:delivery.lead_id,p_event_type:'hive_page.visited',p_properties:{delivery_id:delivery.id}});
 if(event.error)return NextResponse.json({ok:false},{status:500});return NextResponse.json({ok:true,recorded:Boolean(event.data)});
}