'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Hive={id:string;name:string;slug:string};type Member={hive_id:string;business_id:string;businesses:unknown};type Metrics={active_hives:number;active_members:number;visible_leads:number;visible_opportunities:number;open_pipeline:number;attributed_revenue:number};type Biz={name:string};const bizOf=(v:unknown)=>{const x=Array.isArray(v)?v[0]:v;return x&&typeof x==='object'?x as Biz:null};const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export default function Page(){
 const [hives,setHives]=useState<Hive[]>([]),[members,setMembers]=useState<Member[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const auth=await db.auth.getUser();setSignedIn(Boolean(auth.data.user));const [h,m]=await Promise.all([db.from('hives').select('id,name,slug').eq('status','active'),db.from('hive_members').select('hive_id,business_id,businesses(name)').eq('status','active').order('display_order')]);setHives((h.data||[]) as Hive[]);setMembers((m.data||[]) as unknown as Member[]);if(auth.data.user){const mtr=await db.rpc('command_center_metrics');const row=Array.isArray(mtr.data)?mtr.data[0]:mtr.data;if(row)setMetrics(row as Metrics);}setLoading(false);})();},[]);
 const primary=hives[0],primaryMembers=primary?members.filter(m=>m.hive_id===primary.id):[];
 return <Shell><div className="eyebrow">Command Center</div><h1 className="title">Home Hive 360</h1><p className="sub">Your network operating system for turning member-generated demand into measurable opportunity and revenue.</p><div className="grid"><div className="card"><span className="label">Active Hives</span><div className="metric">{loading?'—':hives.length}</div></div><div className="card"><span className="label">Active Members</span><div className="metric">{loading?'—':members.length}</div></div><div className="card"><span className="label">Visible Opportunities</span><div className="metric">{loading?'—':signedIn?metrics?.visible_opportunities??0:'Private'}</div></div><div className="card"><span className="label">Attributed Revenue</span><div className="metric">{loading?'—':signedIn?money(Number(metrics?.attributed_revenue||0)):'Private'}</div></div></div>{!signedIn&&!loading?<section className="section card"><div className="sectionHead"><div><b>Member metrics are protected</b><div className="label">Sign in to see leads, opportunities, pipeline and attributed revenue for businesses you are authorized to access.</div></div><Link className="btn" href="/onboarding">Sign In</Link></div></section>:null}<section className="section two"><div className="card"><div className="sectionHead"><div><b>{primary?.name||'Build your first Hive'}</b><div className="label">Live network status</div></div>{primary?<span className="badge">ACTIVE</span>:null}</div><div className="funnel"><div className="step"><span className="label">Members</span><b>{primaryMembers.length}</b></div><div className="step"><span className="label">Leads</span><b>{signedIn?metrics?.visible_leads??0:'—'}</b></div><div className="step"><span className="label">Opportunities</span><b>{signedIn?metrics?.visible_opportunities??0:'—'}</b></div><div className="step"><span className="label">Open Pipeline</span><b>{signedIn?money(Number(metrics?.open_pipeline||0)):'—'}</b></div></div></div><div className="card"><b>HH360 Value Loop</b><p className="sub" style={{marginTop:10}}>Member marketing creates demand. The Hive creates additional exposure. HH360 attributes the resulting opportunity and revenue.</p><div className="label">Lead → Exposure → Action → Opportunity → Revenue</div></div></section><section className="section card"><div className="sectionHead"><div><b>{primary?.name||'Hive'} Members</b><div className="label">Live member records</div></div></div>{primaryMembers.length?<table className="table"><thead><tr><th>Business</th><th>Status</th><th>Hive</th></tr></thead><tbody>{primaryMembers.map(m=><tr key={m.hive_id+'-'+m.business_id}><td>{bizOf(m.businesses)?.name||'Business'}</td><td><span className="badge">ACTIVE</span></td><td>{primary?.name}</td></tr>)}</tbody></table>:<p className="sub">No active members found.</p>}</section></Shell>;
}
