'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Hive={id:string;name:string;slug:string;status:string;market_name:string|null;headline:string|null;created_by:string|null};
type Member={hive_id:string;business_id:string;status:string;businesses:unknown};
type BusinessView={name:string;slug:string;services:{category:string|null}[]};
const businessOf=(value:unknown):BusinessView|null=>{const v=Array.isArray(value)?value[0]:value;if(!v||typeof v!=='object')return null;return v as BusinessView;};
export default function Hives(){
 const [hives,setHives]=useState<Hive[]>([]),[members,setMembers]=useState<Member[]>([]),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false),[userId,setUserId]=useState(''),[managed,setManaged]=useState<{business_id:string;businesses:unknown}[]>([]),[adding,setAdding]=useState('');
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);setUserId(auth.data.user.id);const [h,m,bu]=await Promise.all([db.from('hives').select('id,name,slug,status,market_name,headline,created_by').order('created_at'),db.from('hive_members').select('hive_id,business_id,status,businesses(name,slug,services(category))').order('display_order'),db.from('business_users').select('business_id,businesses(name,slug)').eq('user_id',auth.data.user.id).in('role',['owner','admin'])]);setHives((h.data||[]) as Hive[]);setMembers((m.data||[]) as unknown as Member[]);setManaged((bu.data||[]) as unknown as {business_id:string;businesses:unknown}[]);setLoading(false);})();},[]);
 async function addMember(hiveId:string,businessId:string){if(!businessId)return;setAdding(hiveId);const db=createBrowserSupabase();await db.rpc('add_managed_business_to_hive',{p_hive_id:hiveId,p_business_id:businessId});location.reload();}
 return <Shell><div className="eyebrow">Network Builder</div><div className="sectionHead"><div><h1 className="title">Hives</h1><p className="sub">Build local networks of complementary home-service businesses.</p></div><Link className="btn" href="/onboarding">+ Create Hive</Link></div>
 {!signedIn&&!loading?<div className="card"><h2>Sign in to manage Hives</h2></div>:null}
 {loading?<div className="card">Loading Hives…</div>:hives.map(h=>{const hm=members.filter(m=>m.hive_id===h.id&&m.status==='active');const categories=new Set(hm.flatMap(m=>businessOf(m.businesses)?.services||[]).map(s=>s.category).filter(Boolean));return <div key={h.id}><div className="card hiveCard"><div><span className="badge">{h.status.toUpperCase()}</span><h2>{h.name}</h2><p className="sub" style={{margin:0}}>{h.market_name||'Local market'} · {hm.length} members · {categories.size} service categories</p></div><div><Link className="btn secondary" href={'/h/'+h.slug}>Preview Hive</Link></div></div><section className="section two"><div className="card"><b>Hive Members</b><table className="table"><tbody>{hm.map(m=>{const b=businessOf(m.businesses);return <tr key={m.business_id}><td>{b?.name||'Business'}</td><td>{b?.services?.[0]?.category||'Home Service'}</td><td><span className="badge">Active</span></td></tr>})}</tbody></table>{hm.length===0?<p className="sub">No active members yet.</p>:null}{h.created_by===userId?<div className="field" style={{marginTop:16}}><label>Add a business you manage</label><select disabled={adding===h.id} defaultValue="" onChange={e=>addMember(h.id,e.target.value)}><option value="" disabled>Select business…</option>{managed.filter(b=>!hm.some(m=>m.business_id===b.business_id)).map(b=>{const bv=businessOf(b.businesses);return <option key={b.business_id} value={b.business_id}>{bv?.name||'Business'}</option>})}</select></div>:null}</div><div className="card"><b>Public Hive Experience</b><p className="sub" style={{marginTop:10}}>{h.headline||"Each member's customers can discover trusted complementary businesses in this Hive."}</p><div className="field"><label>Hive URL</label><input value={'/h/'+h.slug} readOnly/></div><br/><Link className="btn secondary" href={'/h/'+h.slug}>Open Public Page</Link></div></section></div>})}
 </Shell>;
}
