'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Lead={id:string};type Opp={id:string;status:string;estimated_value:number|null;closed_value:number|null};type Event={event_type:string;properties:Record<string,unknown>|null};
export default function Analytics(){
 const [leads,setLeads]=useState<Lead[]>([]),[opps,setOpps]=useState<Opp[]>([]),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);const [l,o,e]=await Promise.all([db.from('leads').select('id').limit(1000),db.from('opportunities').select('id,status,estimated_value,closed_value').limit(1000),db.from('events').select('event_type,properties').order('occurred_at',{ascending:false}).limit(2000)]);setLeads((l.data||[]) as Lead[]);setOpps((o.data||[]) as Opp[]);setEvents((e.data||[]) as Event[]);setLoading(false);})();},[]);
 const m=useMemo(()=>{const exposure=events.filter(e=>['promotion.queued','promotion.sent','promotion.delivered','member.clicked','offer.clicked'].includes(e.event_type)).length;const sent=events.filter(e=>e.event_type==='promotion.sent').length;const delivered=events.filter(e=>e.event_type==='promotion.delivered').length;const clicks=events.filter(e=>['member.clicked','offer.clicked'].includes(e.event_type)).length;const pipeline=opps.filter(o=>!['won','lost'].includes(o.status)).reduce((n,o)=>n+Number(o.estimated_value||0),0);const revenue=opps.reduce((n,o)=>n+Number(o.closed_value||0),0);return{exposure,sent,delivered,clicks,pipeline,revenue,won:opps.filter(o=>o.status==='won').length};},[events,opps]);
 const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
 return <Shell><div className="eyebrow">Hive Intelligence</div><h1 className="title">Analytics</h1><p className="sub">Measure what members contribute and the pipeline, engagement and revenue the Hive creates in return.</p>{!signedIn&&!loading?<section className="section card"><h2>Sign in to view protected Hive analytics</h2></section>:null}<div className="grid"><div className="card"><span className="label">Leads Contributed</span><div className="metric">{loading?'—':leads.length}</div></div><div className="card"><span className="label">Hive Exposure</span><div className="metric">{loading?'—':m.exposure}</div></div><div className="card"><span className="label">Pipeline Generated</span><div className="metric">{loading?'—':money(m.pipeline)}</div></div><div className="card"><span className="label">Revenue Generated</span><div className="metric">{loading?'—':money(m.revenue)}</div></div></div><section className="section card"><div className="sectionHead"><div><b>Promotion Funnel</b><div className="label">Live attribution events visible to your businesses under HH360 access policies.</div></div><span className="badge">LIVE DATA</span></div><div className="funnel" style={{marginTop:14}}><div className="step"><span className="label">Sent</span><b>{loading?'—':m.sent}</b></div><div className="step"><span className="label">Delivered</span><b>{loading?'—':m.delivered}</b></div><div className="step"><span className="label">Clicks</span><b>{loading?'—':m.clicks}</b></div><div className="step"><span className="label">Opportunities</span><b>{loading?'—':opps.length}</b></div><div className="step"><span className="label">Won</span><b>{loading?'—':m.won}</b></div></div></section></Shell>;
}