'use client';
import {useEffect,useMemo,useState} from 'react';
import Shell from '@/components/Shell';
import {createBrowserSupabase} from '@/lib/supabase/browser';
type Lead={id:string;source_business_id:string};type Opp={id:string;source_business_id:string;receiving_business_id:string;status:string;estimated_value:number|null;closed_value:number|null};type Event={event_type:string;occurred_at:string;business_id:string|null;properties:Record<string,unknown>|null};type Business={id:string;name:string};
export default function Analytics(){
 const [leads,setLeads]=useState<Lead[]>([]),[opps,setOpps]=useState<Opp[]>([]),[events,setEvents]=useState<Event[]>([]),[businesses,setBusinesses]=useState<Business[]>([]),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const auth=await db.auth.getUser();if(!auth.data.user){setLoading(false);return;}setSignedIn(true);const [l,o,e,b]=await Promise.all([db.from('leads').select('id,source_business_id').limit(2000),db.from('opportunities').select('id,source_business_id,receiving_business_id,status,estimated_value,closed_value').limit(2000),db.from('events').select('event_type,occurred_at,business_id,properties').order('occurred_at',{ascending:false}).limit(4000),db.from('businesses').select('id,name').order('name')]);setLeads((l.data||[]) as Lead[]);setOpps((o.data||[]) as Opp[]);setEvents((e.data||[]) as Event[]);setBusinesses((b.data||[]) as Business[]);setLoading(false);})();},[]);
 const m=useMemo(()=>{const count=(t:string)=>events.filter(e=>e.event_type===t).length;const clicks=events.filter(e=>['member.clicked','offer.clicked'].includes(e.event_type)).length;const pipeline=opps.filter(o=>!['won','lost'].includes(o.status)).reduce((n,o)=>n+Number(o.estimated_value||0),0);const revenue=opps.reduce((n,o)=>n+Number(o.closed_value||0),0);const delivered=count('promotion.delivered'),created=opps.length,won=opps.filter(o=>o.status==='won').length;return{queued:count('promotion.queued'),sent:count('promotion.sent'),delivered,clicks,accepted:count('opportunity.accepted'),won,pipeline,revenue,clickRate:delivered?Math.round(clicks/delivered*100):0,winRate:created?Math.round(won/created*100):0};},[events,opps]);
 const members=useMemo(()=>businesses.map(b=>{const contributed=leads.filter(l=>l.source_business_id===b.id).length;const received=opps.filter(o=>o.receiving_business_id===b.id);const sourced=opps.filter(o=>o.source_business_id===b.id);const won=received.filter(o=>o.status==='won');return{id:b.id,name:b.name,contributed,received:received.length,sourced:sourced.length,pipeline:received.filter(o=>!['won','lost'].includes(o.status)).reduce((n,o)=>n+Number(o.estimated_value||0),0),revenue:won.reduce((n,o)=>n+Number(o.closed_value||0),0),wins:won.length};}).filter(x=>x.contributed||x.received||x.sourced),[businesses,leads,opps]);
 const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}),pct=(n:number)=>String(n)+'%';
 return <Shell><div className="eyebrow">Hive Intelligence</div><h1 className="title">Analytics</h1><p className="sub">Measure the complete path from member contribution to customer engagement, opportunity and attributed revenue.</p>{!signedIn&&!loading?<section className="section card"><h2>Sign in to view protected Hive analytics</h2></section>:null}<div className="grid"><div className="card"><span className="label">Leads Contributed</span><div className="metric">{loading?'—':leads.length}</div></div><div className="card"><span className="label">Opportunities</span><div className="metric">{loading?'—':opps.length}</div></div><div className="card"><span className="label">Pipeline Generated</span><div className="metric">{loading?'—':money(m.pipeline)}</div></div><div className="card"><span className="label">Revenue Generated</span><div className="metric">{loading?'—':money(m.revenue)}</div></div></div><section className="section card"><div className="sectionHead"><div><b>Attribution Funnel</b><div className="label">Protected HH360 lifecycle events and opportunity records.</div></div><span className="badge">LIVE DATA</span></div><div className="funnel" style={{marginTop:14}}><div className="step"><span className="label">Queued</span><b>{loading?'—':m.queued}</b></div><div className="step"><span className="label">Sent</span><b>{loading?'—':m.sent}</b></div><div className="step"><span className="label">Delivered</span><b>{loading?'—':m.delivered}</b></div><div className="step"><span className="label">Clicks</span><b>{loading?'—':m.clicks}</b></div><div className="step"><span className="label">Accepted</span><b>{loading?'—':m.accepted}</b></div><div className="step"><span className="label">Won</span><b>{loading?'—':m.won}</b></div></div></section><div className="two"><div className="card"><span className="label">Promotion Click Rate</span><div className="metric">{loading?'—':pct(m.clickRate)}</div></div><div className="card"><span className="label">Opportunity Win Rate</span><div className="metric">{loading?'—':pct(m.winRate)}</div></div></div><section className="section card"><div className="sectionHead"><div><b>Member Value Scorecard</b><div className="label">Contribution in versus measurable value returned by the network.</div></div><span className="badge">MEMBER ROI</span></div><div style={{display:'grid',gap:10,marginTop:18}}>{members.length?members.map(x=><div className="step" key={x.id}><div><b>{x.name}</b><div className="label">{x.contributed} leads contributed · {x.sourced} opportunities generated for the Hive</div></div><div style={{textAlign:'right'}}><b>{money(x.revenue)} revenue</b><div className="label">{x.received} opportunities received · {x.wins} won · {money(x.pipeline)} open pipeline</div></div></div>):<div className="label">Member performance will appear as attributed activity is recorded.</div>}</div></section></Shell>;
}