import {NextRequest,NextResponse} from 'next/server';
import {authorizeBusinessKey} from '@/lib/api/businessKey';
import {consumeRateLimit} from '@/lib/api/rateLimit';
type LeadPayload={first_name?:string;last_name?:string;email?:string;phone?:string;zip?:string;service?:string;source?:string;external_lead_id?:string;marketing_email_allowed?:boolean;marketing_sms_allowed?:boolean;metadata?:Record<string,unknown>;hive_id?:string;hive_slug?:string};
const emailOf=(v?:string)=>v?.trim().toLowerCase()||null;
const phoneOf=(v?:string)=>{const d=v?.replace(/\D/g,'')||'';return d.length>=10?d:null;};
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Lead ingestion is not configured.'},{status:503});
 let body:LeadPayload;try{body=await request.json();}catch{return NextResponse.json({error:'Request body must be valid JSON.'},{status:400});}
 const email=emailOf(body.email),phone=phoneOf(body.phone);if(!body.first_name?.trim())return NextResponse.json({error:'Missing required field: first_name'},{status:422});if(!email&&!phone)return NextResponse.json({error:'A valid email or phone is required.'},{status:422});
 const authResult=await authorizeBusinessKey(request,url,secret);if(!authResult.ok)return NextResponse.json({error:authResult.error},{status:authResult.status});const admin=authResult.auth.db,key={id:authResult.auth.keyId,business_id:authResult.auth.businessId};
 const rate=await consumeRateLimit(admin,'lead:'+key.id,120,60);if(!rate.ok)return NextResponse.json({error:rate.error||'Too many requests.'},{status:rate.error?503:429,headers:rate.error?undefined:{'Retry-After':'60'}});
 const memberships=(await admin.from('hive_members').select('hive_id,hives(slug)').eq('business_id',key.business_id).eq('status','active')).data||[];if(!memberships.length)return NextResponse.json({error:'Business is not an active Hive member.'},{status:403});let membership:any=null;if(body.hive_id)membership=memberships.find((m:any)=>m.hive_id===body.hive_id);else if(body.hive_slug)membership=memberships.find((m:any)=>m.hives?.slug===body.hive_slug);else if(memberships.length===1)membership=memberships[0];else return NextResponse.json({error:'Multiple active Hives found. Supply hive_id or hive_slug.'},{status:422});if(!membership)return NextResponse.json({error:'Business is not an active member of the requested Hive.'},{status:403});
 const promotionAllowed=body.marketing_email_allowed===true||body.marketing_sms_allowed===true;
  const atomic=await admin.rpc('ingest_lead_atomic',{p_source_business_id:key.business_id,p_hive_id:membership.hive_id,p_first_name:body.first_name.trim(),p_last_name:body.last_name?.trim()||null,p_email:email,p_phone:phone,p_postal_code:body.zip?.trim()||null,p_external_lead_id:body.external_lead_id||null,p_source_channel:body.source||'api',p_service_requested:body.service||null,p_marketing_email_allowed:body.marketing_email_allowed===true,p_marketing_sms_allowed:body.marketing_sms_allowed===true,p_metadata:{...(body.metadata||{})},p_opportunities:[]});
 if(atomic.error)return NextResponse.json({error:'Could not ingest lead atomically.'},{status:500});const result=atomic.data;return NextResponse.json({lead_id:result.lead_id,received_at:result.received_at,duplicate:Boolean(result.duplicate),promotion_eligible:promotionAllowed,audience_eligible:promotionAllowed,opportunities_created:0},{status:result.duplicate?200:201});
}