import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {createHash} from 'crypto';
import {rankPromotionCandidates} from '@/lib/promotion/rank';
type LeadPayload={first_name?:string;last_name?:string;email?:string;phone?:string;zip?:string;service?:string;source?:string;external_lead_id?:string;marketing_email_allowed?:boolean;marketing_sms_allowed?:boolean;metadata?:Record<string,unknown>;hive_id?:string;hive_slug?:string};
const emailOf=(v?:string)=>v?.trim().toLowerCase()||null;
const phoneOf=(v?:string)=>{const d=v?.replace(/\D/g,'')||'';return d.length>=10?d:null;};
export async function POST(request:NextRequest){
 const apiKey=request.headers.get('x-hh360-key');if(!apiKey)return NextResponse.json({error:'Missing x-hh360-key credential.'},{status:401});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Lead ingestion is not configured.'},{status:503});
 let body:LeadPayload;try{body=await request.json();}catch{return NextResponse.json({error:'Request body must be valid JSON.'},{status:400});}
 const email=emailOf(body.email),phone=phoneOf(body.phone);if(!body.first_name?.trim())return NextResponse.json({error:'Missing required field: first_name'},{status:422});if(!email&&!phone)return NextResponse.json({error:'A valid email or phone is required.'},{status:422});
 const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const keyHash=createHash('sha256').update(apiKey).digest('hex');
 const key=(await admin.from('business_api_keys').select('id,business_id').eq('key_hash',keyHash).eq('is_active',true).maybeSingle()).data;if(!key)return NextResponse.json({error:'Invalid API key.'},{status:401});
 await admin.from('business_api_keys').update({last_used_at:new Date().toISOString()}).eq('id',key.id);
 const memberships=(await admin.from('hive_members').select('hive_id,hives(slug)').eq('business_id',key.business_id).eq('status','active')).data||[];if(!memberships.length)return NextResponse.json({error:'Business is not an active Hive member.'},{status:403});let membership:any=null;if(body.hive_id)membership=memberships.find((m:any)=>m.hive_id===body.hive_id);else if(body.hive_slug)membership=memberships.find((m:any)=>m.hives?.slug===body.hive_slug);else if(memberships.length===1)membership=memberships[0];else return NextResponse.json({error:'Multiple active Hives found. Supply hive_id or hive_slug.'},{status:422});if(!membership)return NextResponse.json({error:'Business is not an active member of the requested Hive.'},{status:403});
 if(body.external_lead_id){const existing=(await admin.from('leads').select('id,received_at').eq('source_business_id',key.business_id).eq('external_lead_id',body.external_lead_id).maybeSingle()).data;if(existing)return NextResponse.json({lead_id:existing.id,received_at:existing.received_at,duplicate:true},{status:200});}
 let customerId:string|null=null;
 if(email)customerId=(await admin.from('customers').select('id').eq('source_business_id',key.business_id).eq('email',email).limit(1).maybeSingle()).data?.id||null;
 if(!customerId&&phone)customerId=(await admin.from('customers').select('id').eq('source_business_id',key.business_id).eq('phone',phone).limit(1).maybeSingle()).data?.id||null;
 if(!customerId){const made=await admin.from('customers').insert({source_business_id:key.business_id,first_name:body.first_name.trim(),last_name:body.last_name?.trim()||null,email,phone,postal_code:body.zip?.trim()||null}).select('id').single();if(made.error)return NextResponse.json({error:'Could not create customer.'},{status:500});customerId=made.data.id;}
 const madeLead=await admin.from('leads').insert({source_business_id:key.business_id,hive_id:membership.hive_id,customer_id:customerId,external_lead_id:body.external_lead_id||null,source_channel:body.source||'api',service_requested:body.service||null,status:'received',marketing_email_allowed:body.marketing_email_allowed===true,marketing_sms_allowed:body.marketing_sms_allowed===true,metadata:body.metadata||{}}).select('id,received_at').single();if(madeLead.error)return NextResponse.json({error:'Could not create lead.'},{status:500});const lead=madeLead.data;
 await admin.from('events').insert({hive_id:membership.hive_id,business_id:key.business_id,customer_id:customerId,lead_id:lead.id,event_type:'lead.received',actor_type:'system',properties:{source:body.source||'api',service:body.service||null}});
 let opportunityCount=0;const promotionAllowed=body.marketing_email_allowed===true||body.marketing_sms_allowed===true;
 if(promotionAllowed){const members=(await admin.from('hive_members').select('business_id,businesses(name,services(category))').eq('hive_id',membership.hive_id).eq('status','active')).data||[];const ids=members.map((m:any)=>m.business_id).filter((id:string)=>id!==key.business_id);const offers=ids.length?(await admin.from('offers').select('id,business_id,title').eq('hive_id',membership.hive_id).eq('status','active').in('business_id',ids)).data||[]:[];const offerBy=new Map(offers.map((o:any)=>[o.business_id,o]));const candidates=members.map((m:any)=>{const offer:any=offerBy.get(m.business_id);return{businessId:m.business_id,businessName:m.businesses?.name||'Hive Member',category:m.businesses?.services?.[0]?.category||null,offerId:offer?.id,offerTitle:offer?.title};});const selected=rankPromotionCandidates({sourceBusinessId:key.business_id,serviceRequested:body.service,members:candidates});if(selected.length){const rows=selected.map(x=>({hive_id:membership.hive_id,lead_id:lead.id,source_business_id:key.business_id,receiving_business_id:x.businessId,customer_id:customerId,offer_id:x.offerId||null}));const created=(await admin.from('opportunities').insert(rows).select('id,receiving_business_id')).data||[];opportunityCount=created.length;if(created.length)await admin.from('events').insert(created.map(o=>({hive_id:membership.hive_id,business_id:o.receiving_business_id,customer_id:customerId,lead_id:lead.id,event_type:'opportunity.created',actor_type:'system',properties:{source_business_id:key.business_id,opportunity_id:o.id,selection:'promotion_rules_v1'}})));}}
 return NextResponse.json({lead_id:lead.id,received_at:lead.received_at,promotion_eligible:promotionAllowed,opportunities_created:opportunityCount},{status:201});
}