import {NextRequest,NextResponse} from 'next/server';
import {authorizeBusinessKey} from '@/lib/api/businessKey';
import {consumeRateLimit} from '@/lib/api/rateLimit';
import {buildPromotionMessage} from '@/lib/promotion/message';
export async function POST(request:NextRequest){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!url||!secret)return NextResponse.json({error:'Not configured'},{status:503});
 let body:{lead_id?:string};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}if(!body.lead_id)return NextResponse.json({error:'Missing lead_id'},{status:422});
 const authResult=await authorizeBusinessKey(request,url,secret);if(!authResult.ok)return NextResponse.json({error:authResult.error},{status:authResult.status});const auth=authResult.auth,db=auth.db;const rate=await consumeRateLimit(db,'promotion:queue:'+auth.keyId,60,60);if(!rate.ok)return NextResponse.json({error:rate.error||'Rate limit exceeded'},{status:rate.error?503:429,headers:rate.error?undefined:{'Retry-After':'60'}});const lead=(await db.from('leads').select('id,hive_id,source_business_id,customer_id,marketing_email_allowed,marketing_sms_allowed').eq('id',body.lead_id).maybeSingle()).data;if(!lead)return NextResponse.json({error:'Lead not found'},{status:404});if(lead.source_business_id!==auth.businessId)return NextResponse.json({error:'Forbidden'},{status:403});
 const customer=(await db.from('customers').select('first_name,email,phone').eq('id',lead.customer_id).maybeSingle()).data,source=(await db.from('businesses').select('name,slug').eq('id',lead.source_business_id).maybeSingle()).data,hive=(await db.from('hives').select('slug,market_name').eq('id',lead.hive_id).maybeSingle()).data;if(!customer||!source||!hive)return NextResponse.json({error:'Promotion context incomplete'},{status:409});
 const channels:string[]=[];if(lead.marketing_email_allowed&&customer.email)channels.push('email');if(lead.marketing_sms_allowed&&customer.phone)channels.push('sms');if(!channels.length)return NextResponse.json({error:'No consented delivery channel available'},{status:403});
 const origin=process.env.NEXT_PUBLIC_APP_URL;let base;try{base=buildPromotionMessage({firstName:customer.first_name||'there',sourceBusinessName:source.name,hiveSlug:hive.slug,sourceBusinessSlug:source.slug,marketName:hive.market_name,appOrigin:origin});}catch{return NextResponse.json({error:'Promotion link configuration unavailable'},{status:503});}
 const deliveries:any[]=[];for(const channel of channels){const queued=await db.rpc('queue_promotion_delivery_atomic',{p_lead_id:lead.id,p_channel:channel});if(queued.error)return NextResponse.json({error:'Could not queue promotion'},{status:500});deliveries.push(queued.data);}
 return NextResponse.json({lead_id:lead.id,status:'queued',deliveries:deliveries.map(d=>({id:d.id,channel:d.channel,status:d.status,created:d.created,hive_url:base.hiveUrl+(base.hiveUrl.includes('?')?'&':'?')+'pid='+encodeURIComponent(d.tracking_token),message:d.channel==='email'?{subject:base.emailSubject,text:base.emailText}:{text:base.smsText}}))});
}