import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {consumeRateLimit} from '@/lib/api/rateLimit';
const allowed=['new','accepted','contacted','qualified','won','lost'];
const transitions:Record<string,string[]>={new:['accepted','contacted','qualified','won','lost'],accepted:['contacted','qualified','won','lost'],contacted:['qualified','won','lost'],qualified:['won','lost'],won:[],lost:[]};
export async function PATCH(request:NextRequest,context:{params:Promise<{id:string}>}){
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY,pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!secret||!pub)return NextResponse.json({error:'Not configured'},{status:503});
 const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return NextResponse.json({error:'Authentication required'},{status:401});const auth=createClient(url,pub,{auth:{persistSession:false,autoRefreshToken:false}});const user=(await auth.auth.getUser(token)).data.user;if(!user)return NextResponse.json({error:'Invalid session'},{status:401});
 const {id}=await context.params;let body:{status?:string;estimated_value?:number;closed_value?:number};try{body=await request.json();}catch{return NextResponse.json({error:'Invalid JSON'},{status:400});}
 if(body.status&&!allowed.includes(body.status))return NextResponse.json({error:'Invalid status'},{status:422});for(const [name,value] of [['estimated_value',body.estimated_value],['closed_value',body.closed_value]] as const){if(value!==undefined&&(!Number.isFinite(value)||value<0))return NextResponse.json({error:name+' must be a non-negative number'},{status:422});}
 const admin=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const rate=await consumeRateLimit(admin,'opportunity:user:'+user.id,120,60);if(!rate.ok)return NextResponse.json({error:rate.error||'Rate limit exceeded'},{status:rate.error?503:429,headers:rate.error?undefined:{'Retry-After':'60'}});const opp=(await admin.from('opportunities').select('id,status,estimated_value,closed_value,hive_id,lead_id,customer_id,receiving_business_id').eq('id',id).maybeSingle()).data;if(!opp)return NextResponse.json({error:'Opportunity not found'},{status:404});
 const membership=(await admin.from('business_users').select('role').eq('business_id',opp.receiving_business_id).eq('user_id',user.id).in('role',['owner','admin','manager']).maybeSingle()).data;if(!membership)return NextResponse.json({error:'Forbidden'},{status:403});
 if(body.status&&body.status!==opp.status&&!(transitions[opp.status]||[]).includes(body.status))return NextResponse.json({error:'Invalid opportunity transition',from:opp.status,to:body.status},{status:409});
 const patch:Record<string,unknown>={};if(body.status!==undefined)patch.status=body.status;if(body.estimated_value!==undefined)patch.estimated_value=body.estimated_value;if(body.closed_value!==undefined)patch.closed_value=body.closed_value;if(!Object.keys(patch).length)return NextResponse.json({error:'No changes supplied'},{status:422});
 const atomic=await admin.rpc('update_opportunity_atomic',{p_id:id,p_expected_status:opp.status,p_status:body.status??null,p_estimated_value:body.estimated_value??null,p_closed_value:body.closed_value??null,p_actor_user_id:user.id});
 if(atomic.error){const changed=atomic.error.message?.includes('opportunity_changed');return NextResponse.json({error:changed?'Opportunity changed concurrently; reload and retry':'Atomic lifecycle update failed'},{status:changed?409:500});}
 return NextResponse.json({opportunity:atomic.data,audited:true});
}