'use client';
import { useEffect,useState } from 'react';
import Shell from '@/components/Shell';
import { createBrowserSupabase } from '@/lib/supabase/browser';

type Lead={id:string;status:string;source_channel:string|null;service_requested:string|null;received_at:string;marketing_email_allowed:boolean;marketing_sms_allowed:boolean};
export default function Leads(){
 const [rows,setRows]=useState<Lead[]>([]),[stats,setStats]=useState({received:0,processed:0,promotion_eligible:0}),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{(async()=>{const db=createBrowserSupabase();const {data:{user}}=await db.auth.getUser();if(!user){setLoading(false);return;}setSignedIn(true);const [q,m]=await Promise.all([db.from('leads').select('id,status,source_channel,service_requested,received_at,marketing_email_allowed,marketing_sms_allowed').order('received_at',{ascending:false}).limit(100),db.rpc('lead_hub_metrics')]);setRows((q.data||[]) as Lead[]);const metric=Array.isArray(m.data)?m.data[0]:m.data;if(metric)setStats(metric);setLoading(false);})();},[]);
 return <Shell>
  <div className="eyebrow">Demand Engine</div><h1 className="title">Lead Hub</h1><p className="sub">Every member-generated lead enters the Hub, keeps its source attribution and can create new Hive exposure.</p>
  <div className="grid"><div className="card"><span className="label">Leads Received</span><div className="metric">{loading?'—':stats.received}</div></div><div className="card"><span className="label">Processed</span><div className="metric">{loading?'—':stats.processed}</div></div><div className="card"><span className="label">Promotion Eligible</span><div className="metric">{loading?'—':stats.promotion_eligible}</div></div><div className="card"><span className="label">Privacy</span><div className="metric">RLS</div><span className="label">Source-owned data</span></div></div>
  <section className="section card"><div className="sectionHead"><div><b>Recent Leads</b><div className="label">Only leads generated by businesses you are authorized to access</div></div><span className="badge">PRIVATE</span></div>
   {!signedIn&&!loading?<div style={{padding:'34px 0',textAlign:'center'}}><h2>Sign in to view leads</h2><p className="sub">Member customer data is never pooled across the Hive.</p></div>:null}
   {signedIn&&!loading&&rows.length===0?<div style={{padding:'34px 0',textAlign:'center'}}><h2>No leads yet</h2><p className="sub">Connected forms, CRMs and automations will appear here as leads enter the Hub.</p></div>:null}
   {rows.length?<div style={{display:'grid',gap:10,marginTop:18}}>{rows.map(r=><div className="step" key={r.id}><div><span className="label">{new Date(r.received_at).toLocaleString()}</span><b style={{display:'block'}}>{r.service_requested||'General home service'}</b><span className="label">{r.source_channel||'api'} · {r.id.slice(0,8)}</span></div><div><span className="badge">{(r.marketing_email_allowed||r.marketing_sms_allowed)?'HIVE ELIGIBLE':'SOURCE ONLY'}</span></div></div>)}</div>:null}
  </section>
  <section className="section card"><div className="sectionHead"><div><b>Universal Lead Flow</b><div className="label">One ingestion contract for website forms, CRMs and automation platforms</div></div><span className="badge">LIVE API</span></div><div className="funnel" style={{marginTop:14}}><div className="step"><span className="label">Member Marketing</span><b>Lead</b></div><div className="step"><span className="label">HH360 Hub</span><b>Validate</b></div><div className="step"><span className="label">Consent + Rules</span><b>Eligible</b></div><div className="step"><span className="label">Home Hive</span><b>Expose</b></div><div className="step"><span className="label">Opportunity</span><b>Attribute</b></div></div></section>
 </Shell>;
}
